# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Auto Self Report
on: 
  push:
    branches:
      - main
  schedule:
  - cron: "5 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Actions
      uses: actions/checkout@v1

   
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install yagmail

    - name: Auto Daily Report
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
      run: |
        python ./dailyFudan.py